"""
DOCX monthly report generator.

Takes the profile, score, narrative, and recommendations, and produces a
formatted Word document. The DOCX is one of the listed competition deliverables.

Charts are passed in as in-memory PNG bytes (generated by Plotly+kaleido in app.py),
so this module has no Plotly dependency itself.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Iterable

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from models import FinancialProfile, WellnessScore, RecommendationSet


GRADE_COLORS = {
    "A+": RGBColor(0x1B, 0x5E, 0x20),
    "A":  RGBColor(0x2E, 0x7D, 0x32),
    "B":  RGBColor(0xF9, 0xA8, 0x25),
    "C":  RGBColor(0xEF, 0x6C, 0x00),
    "D":  RGBColor(0xC6, 0x28, 0x28),
}


def build_report(
    profile: FinancialProfile,
    score: WellnessScore,
    narrative: str,
    recommendations: RecommendationSet,
    chart_images: Iterable[bytes] = (),
) -> bytes:
    """Build the DOCX in memory and return its bytes (for st.download_button)."""
    doc = Document()

    # Default font
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # --- Cover ---
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("Personal Finance Health Report")
    run.bold = True
    run.font.size = Pt(24)

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.add_run(f"Prepared for {profile.user_name}").italic = True
    sub.add_run(f"\n{datetime.now().strftime('%B %Y')}")

    doc.add_paragraph()  # spacer

    # --- Score headline ---
    score_para = doc.add_paragraph()
    score_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    score_run = score_para.add_run(f"{score.total:.0f}/100   ·   Grade {score.grade}")
    score_run.bold = True
    score_run.font.size = Pt(22)
    score_run.font.color.rgb = GRADE_COLORS.get(score.grade, RGBColor(0, 0, 0))

    headline_para = doc.add_paragraph()
    headline_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    headline_para.add_run(score.headline).italic = True

    doc.add_paragraph()

    # --- Component breakdown ---
    doc.add_heading("Score Breakdown", level=1)
    table = doc.add_table(rows=1, cols=4)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text = "Component"
    hdr[1].text = "Score"
    hdr[2].text = "Metric"
    hdr[3].text = "What this means"
    for c in score.components:
        row = table.add_row().cells
        row[0].text = c.name
        row[1].text = f"{c.score:.0f} / {c.max_score:.0f}"
        row[2].text = f"{c.metric_value:.1f} {c.metric_unit}".strip()
        row[3].text = c.explanation

    # --- Charts ---
    for png_bytes in chart_images:
        if png_bytes:
            doc.add_paragraph()
            doc.add_picture(io.BytesIO(png_bytes), width=Inches(6.0))

    # --- Narrative ---
    doc.add_heading("Your Financial Picture", level=1)
    for para in narrative.split("\n\n"):
        if para.strip():
            doc.add_paragraph(para.strip())

    # --- Recommendations ---
    doc.add_heading("3 Prioritised Recommendations", level=1)
    for i, rec in enumerate(recommendations.recommendations, 1):
        h = doc.add_heading(f"{i}. {rec.title}", level=2)
        meta = doc.add_paragraph()
        meta.add_run(f"Priority: ").bold = True
        meta.add_run(f"{rec.priority.upper()}   ·   ")
        meta.add_run(f"Category: ").bold = True
        meta.add_run(rec.category.title())

        doc.add_paragraph().add_run("Expected impact: ").bold = True
        doc.paragraphs[-1].add_run(rec.expected_impact)

        doc.add_paragraph().add_run("Why this matters for you: ").bold = True
        doc.paragraphs[-1].add_run(rec.rationale)

        doc.add_paragraph("Action steps:").runs[0].bold = True
        for step in rec.action_steps:
            doc.add_paragraph(step, style="List Bullet")

    # --- Footer note ---
    doc.add_paragraph()
    footnote = doc.add_paragraph()
    note = footnote.add_run(
        "Generated by the Personal Finance Health Report system. "
        "Benchmarks are derived from NSSO 68th Round and RBI DBIE aggregate household data. "
        "AI-generated content is interpretive — figures and scores are deterministically computed."
    )
    note.italic = True
    note.font.size = Pt(9)
    note.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    # Serialise
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
